[2025-03-04T23:57:34.203+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T23:57:34.214+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: AlphaVantage_Stock_Price_Prediction.train_model manual__2025-03-04T23:55:47.119292+00:00 [queued]>
[2025-03-04T23:57:34.217+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: AlphaVantage_Stock_Price_Prediction.train_model manual__2025-03-04T23:55:47.119292+00:00 [queued]>
[2025-03-04T23:57:34.218+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-04T23:57:34.223+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_model> on 2025-03-04 23:55:47.119292+00:00
[2025-03-04T23:57:34.228+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=344) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-04T23:57:34.228+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'AlphaVantage_Stock_Price_Prediction', 'train_model', 'manual__2025-03-04T23:55:47.119292+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/stockpriceprediction.py', '--cfg-path', '/tmp/tmpjq4gsynx']
[2025-03-04T23:57:34.230+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask train_model
[2025-03-04T23:57:34.229+0000] {standard_task_runner.py:72} INFO - Started process 347 to run task
[2025-03-04T23:57:34.254+0000] {task_command.py:467} INFO - Running <TaskInstance: AlphaVantage_Stock_Price_Prediction.train_model manual__2025-03-04T23:55:47.119292+00:00 [running]> on host c8e2f43182e0
[2025-03-04T23:57:34.293+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='AlphaVantage_Stock_Price_Prediction' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T23:55:47.119292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-04T23:55:47.119292+00:00'
[2025-03-04T23:57:34.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-04T23:57:34.839+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-04T23:58:51.093+0000] {job.py:229} INFO - Heartbeat recovered after 36.36 seconds
[2025-03-04T23:59:09.022+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-04T23:59:10.971+0000] {cursor.py:1156} INFO - Number of results in first chunk: 14
[2025-03-04T23:59:10.973+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-04T23:59:11.011+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-04T23:59:11.012+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=AlphaVantage_Stock_Price_Prediction, task_id=train_model, run_id=manual__2025-03-04T23:55:47.119292+00:00, execution_date=20250304T235547, start_date=20250304T235734, end_date=20250304T235911
[2025-03-04T23:59:11.095+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T23:59:11.108+0000] {taskinstance.py:3925} ERROR - Error scheduling downstream tasks. Skipping it as this is entirely optional optimisation. There might be various reasons for it, please take a look at the stack trace to figure out if the root cause can be diagnosed and fixed. See the issue https://github.com/apache/***/issues/39717 for details and an example problem. If you would like to get help in solving root cause, open discussion with all details with your managed service support or in Airflow repository.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3921, in schedule_downstream_tasks
    return TaskInstance._schedule_downstream_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3870, in _schedule_downstream_tasks
    partial_dag = task.dag.partial_subset(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2664, in partial_subset
    t.task_id: _deepcopy_task(t)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2661, in _deepcopy_task
    return copy.deepcopy(t, memo)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 143, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1388, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 201, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object
[2025-03-04T23:59:11.115+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
